### ISSUE TITLE
FileExistsError: dea-sync

### ISSUE THREAD

**Issue by santoshamohan** [GeoscienceAustralia/ga-datacube-env#201]
When two or more `dea-sync` jobs run at the same time for a given product, these `sync` try to access the same `cache` file and reports following error.

```
Traceback (most recent call last):
  File "/g/data/v10/public/modules/dea/20181213/bin/dea-sync", line 11, in <module>
    sys.exit(cli())
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/datacube/ui/click.py", line 190, in new_func
    return f(parsed_config, *args, **kwargs)
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/datacube/ui/click.py", line 218, in with_index
    return f(index, *args, **kwargs)
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/__init__.py", line 95, in cli
    **fix_settings
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/fixes.py", line 108, in fix_mismatches
    for mismatch in mismatches:
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/__init__.py", line 163, in get_mismatches
    workers=job_count
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/scan.py", line 154, in mismatches_for_collection
    path_dawg = build_pathset(collection, cache_folder, log=log)
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/scan.py", line 69, in build_pathset
    with fileutils.atomic_save(str(locations_cache)) as f:
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/boltons/fileutils.py", line 429, in __enter__
    self.setup()
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/boltons/fileutils.py", line 425, in setup
    self._open_part_file()
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/boltons/fileutils.py", line 390, in _open_part_file
    fd = os.open(self.part_path, self.open_flags, file_perms)
FileExistsError: [Errno 17] File exists: '/g/data/v10/work/sync/ls5_pq_scene/2018-12-24T1112/cache/product_ls5_pq_scene/locations.dawg.part'
```

**Comment by jeremyh** [comment]
I noticed this! This last line should probably be an error/exception, not an (easily missable) warning:
https://github.com/GeoscienceAustralia/digitalearthau/blob/b69c6820cf6a98e59165875dcb9f206288fa5235/digitalearthau/sync/submit_job.py#L361-L364

(it may fail anyway, if two jobs are running in the same second, as one job may create the directory after the other's `exists()` check)

**Comment by jeremyh** [comment]
See previous behaviour: https://github.com/GeoscienceAustralia/digitalearthau/commit/db50e9e6d08d1f6e4494f8e8fb58d34ae566ec26#diff-b727d9e0c89f11d1f551285fe3093c95L358

Note that dea-sync allows you to specify the work directory as a parameter, so you could explicitly give jobs separate folders, rather than the default time-based names (assuming that's not already being done -- I'm a bit ignorant of the lambda setup).

**Comment by santoshamohan** [comment]
The `FileExistsError` issue I have noticed is when an attempt is made to write to the cache file that already exists.

I suspect the following code, please suggest:
https://github.com/GeoscienceAustralia/digitalearthau/blob/0ebf5e38dc16c637235d5fbb41944ff4b69eabb7/digitalearthau/sync/scan.py#L54-L69

Though `cache` file has been created recently by the `sync` process, the logic considers that the `cache` is old and new `cache` (`locations.dawg`) file is created/updated.

**Comment by jeremyh** [comment]
The default definition of "old" for caches is defined here: https://github.com/GeoscienceAustralia/digitalearthau/blob/0ebf5e38dc16c637235d5fbb41944ff4b69eabb7/digitalearthau/sync/scan.py#L28-L29

The cache is usually pre-built on job submission. My guess is that more than this time elapsed while the jobs sat in the pbs queue. So, as soon as they started, multiple jobs tried to update the cache at once.

Options:
1. Allow multiple processes to create the cache at once: pass a  unique `part_filename` attribute to  `fileutils.atomic_save` of each process). Easy change with _minor_ drop in efficiency when this happens.
2. Increase the allowed cache age. 
      - If the jobs are once-a-week, we could set it to multiple days.
      - If the jobs are daily, it could be slightly higher. (it needs to be low enough that the next pbs submission will still update the cache) 20 hours?

1 would avoid the error, and 2 would make cache recreation a rare(r) occurrence.

Alternatively 3: Have other processes wait while one creates a cache. But this would take locks and be a little more error prone.
